const products = [
    {
      id: 1,
      name: "El Temor del Hombre Sabio",
      price: 2300,
      image: "/libro_el_temor_del_hombre_sabio.webp",
      author: "",
      description: "El Temor del Hombre Sabio",
      category: "Autoayuda",
      stock: 10,
    },
    {
      id: 2,
      name: "El Mito de la Libertad",
      price: 4500,
      image: "/libro_el_mito_de_la_libertad.webp",
      author: "",
      description: "El Mito de la Libertad",
      category: "Autoayuda",
      stock: 10,
    },
    {
      id: 3,
      name: "Numerologia",
      price: 1100,
      image: "/libro_numerologia.webp",
      author: "",
      description: "Numerlogia",
      category: "Autoayuda",
      stock: 10,
    },
    {
      id: 4,
      name: "libro de Oro",
      price: 3200,
      image: "/libro_de_oro.webp",
      author: "",
      description: "libro de Oro",
      category: "Autoayuda",
      stock: 10,
    },
    {
      id: 5,
      name: "La Conciencia sin Fronteras",
      price: 4000,
      image: "/libro_la_conciencia_sin_fronteras.webp",
      author: "",
      description: "La Conciencia sin Fronteras",
      category: "Autoayuda",
      stock: 10,
    },
    {
      id: 6,
      name: "Manual de Mindfulness",
      price: 1800,
      image: "/libro_manual_de_mindfulness.webp",
      author: "",
      description: "Manual de Mindfulness",
      category: "Autoayuda",
      stock: 10,
    },
    {
      id: 7,
      name: "Chamanismo Cuantico",
      price: 2800,
      image: "/libro_chamanismo_cuantico.webp",
      author: "",
      description: "Chamanismo Cuantico",
      category: "Autoayuda",
      stock: 10,
    },
    {
      id: 8,
      name: "Decide de Nuevo",
      price: 3300,
      image: "/libro_decide_de_nuevo.webp",
      author: "",
      description: "Decide de Nuevo",
      category: "Autoayuda",
      stock: 10,
    },
    {
      id: 9,
      name: "Espabila de una Puta Vez",
      price: 2500,
      image: "/libro_espabila_de_una_puta_vez.jpg",
      author: "",
      description: "Espabila de una Puta Vez",
      category: "Autoayuda",
      stock: 10,
    },
    {
      id: 10,
      name: "La Espiritualidad del Exito",
      price: 5500,
      image: "/libro_la_espiritualidad_del_exito.jpg",
      author: "",
      description: "La Espiritualidad del Exito",
      category: "Autoayuda",
      stock: 10,
    },
  ];
  
  export default products;
  